### ISSUE TITLE
lines have spikes (specially in higher map zool level) when there are many segments 

### ISSUE THREAD

**Issue by atajadod** [conveyal/transitive.js#58]
#### When drawing path with many segments, some spikes appears. Please take a look at the image below:
![image](https://user-images.githubusercontent.com/22226147/98312498-b9e7ff80-1f86-11eb-92d9-e6de9abfa9ca.png)

After digging a bit, it seems the issue indeed is because of the lineJoin settings of the Canvas. The default is "miter".

## Proposed solution:
If I add the following line to drawPath function inside canvas-display.js, it would solve this issue
```
this.ctx.lineJoin = 'round';
```
##### Here is what it looks after adding the line above:
![image](https://user-images.githubusercontent.com/22226147/98313298-5c54b280-1f88-11eb-9293-a39f381a0799.png)

I am suggesting to add the line below to drawPath in canvas-display.js 
```
this.ctx.lineJoin = attrs['lineJoin'] || 'miter';
```
![image](https://user-images.githubusercontent.com/22226147/98312899-7d68d380-1f87-11eb-8239-a8e276976684.png)

and the line below in the render function inside renderedsegment.js
```
display.drawPath(this.renderData, {
        fill: 'none',
        stroke: styler.compute2('segments', 'stroke', this),
        'stroke-width': styler.compute2('segments', 'stroke-width', this),
        'stroke-dasharray': styler.compute2('segments', 'stroke-dasharray', this),
        'stroke-linecap': styler.compute2('segments', 'stroke-linecap', this),
        'lineJoin':'round',
      });
```
![image](https://user-images.githubusercontent.com/22226147/98312965-a7ba9100-1f87-11eb-8902-ee0e1e4f38e0.png)

**Comment by landonreed** [comment]
Hi @atajadod, thanks so much for your bug report/suggestion. Would you be able to share the itinerary JSON from OpenTripPlanner that is giving you trouble so that we can reproduce this and test the `lineJoin` property?

**Comment by atajadod** [comment]
Hi @landonreed 
Sorry for delayed response. 
Of course, You can use our test server at https://tptest.actransit.org. you can use the link below to produce the same result,
[El Cerrito City Hall, El Cerrito  To  Market Street & South Van Ness Avenue, San Francisco](https://tptest.actransit.org/#/?ui_activeSearch=idn2h68vh&ui_activeItinerary=0&fromPlace=El%20Cerrito%20City%20Hall%2C%20El%20Cerrito%2C%20USA%3A%3A37.91572%2C-122.31104&toPlace=Market%20Street%20%26%20South%20Van%20Ness%20Avenue%2C%20San%20Francisco%2C%20USA%3A%3A37.775436%2C-122.418737&date=2020-11-17&time=04%3A30&arriveBy=false&mode=WALK%2CBUS%2CTRAM%2CFERRY&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=)

Please note:
- I have already applied the fix,I mentioned above, there.
- Due to issue we had with interStopGeometry not being returned from our engine, we are rendering legGeometry for each leg.
