### ISSUE TITLE
LabeledModes.Include is throwing an error

### ISSUE THREAD

**Issue by avjolsakaj** [conveyal/transitive.js#69]
This line of code was throwing error: labeledModes.includes(....).
Error: Can not use includes on undefined property.

Solution is just make safety check after labeledModes like this:
`const labeledModes = this.transitive.options.labeledModes 
....
if (segment.type === 'TRANSIT' && labeledModes?.includes(segment.getMode()))
....`

**Comment by binh-dam-ibigroup** [comment]
Hello @avjolsakaj, thank you for reporting this oversight. I submitted #70 to fix. Meanwhile, a workaround to this issue is to specify `labeledModes` as an option to `new Transitive()`, as in:
```js
new Transitive({
      data: transitiveData,
      labeledModes: [2, 3], // label the RAIL (2) and BUS (3) OTP modes
      // ... other parameters
    })
```
